### ISSUE TITLE
not a homepage, give me the real one

### ISSUE THREAD

**Issue by Interleace** [Div685/youtube-homepage#9]
could you make a real start/home/first page? :3
I mean, that's not what the title says, is it?

**Comment by Div685** [comment]
Yes, I can make it but the youtube home page is simple and it only has a list of videos. The main goal for this project was for me to practice HTML and CSS to clone [this page](https://www.youtube.com/watch?v=V74l_zS1x8E). My apology for not providing enough information on the README.md file.
